spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: mock-google-client-id
            client-secret: mock-google-client-secret
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: "http://localhost:8080/mock/oauth2/authorize"
            token-uri: "http://localhost:8080/mock/oauth2/token"
            user-info-uri: "http://localhost:8080/mock/oauth2/userinfo"
            user-name-attribute: sub

server:
  port: 8080

front:
  redirect: ''